### PR TITLE
Move validate script to scripts folder

### PR DESCRIPTION
**Pull request by c-w**
Also: make compatible with Python 3.5

### CODE REVIEW

**Review by michaelperel — CHANGES_REQUESTED** [review]
I do not think we should downgrade from python 3.6 -> 3.5 . Standard practice assumes using a virtual environment, which means even if 3.5 is the default, we can use a virtual environment with 3.6.

**Comment by c-w** [comment]
For creating a Python 3.6 virtualenv, you still need to have a Python 3.6 interpreter on your system which is not the default for many systems including Ubuntu 16.04 which we advertise as the deployment environment for the repo.

**Comment by c-w** [comment]
In any case, then please add a requirements.txt and move the script to the scripts folder.

**Comment by michaelperel** [comment]
Will definitely add a requirements.txt and move the script. Thanks for the headsup. When I wrote the readme, everything ran in docker containers. Now that we are using docker-py and cannot run that part of the application in a container, the readme needs to be updated. Once the project settles down a bit, I will make sure the readme reflects the new work. Thanks!

**Pull request closed without merging**
